export const FETCH_RECIPE_REQUEST = 'FETCH_RECIPE_REQUEST';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';
export const FETCH_RECIPE_FAILURE = 'FETCH_RECIPE_FAILURE';
export const SELECT_RECIPE = 'SELECT_RECIPE';
export const SET_FAVOURITE = 'SET_FAVOURITE';
export const UPDATE_STAR_RATING = 'UPDATE_STAR_RATING';
